import { ILevel } from "../types/Level";
import { EnemyTankStandard, EnemyTankRapid, EnemyTankHeavy, EnemyTankStrong } from '../actors/EnemyTankClasses';

/*
    . = whithespace
    % = player spawnpoint
    * = enemy spawnpoint
    O = destrutible block

*/


const Level0: ILevel = {
    id: 'Level0',

    map: `.............
    .............
    .............
    .............
    .............
    .............
    .............
    .............
    .............
    .............
    .............
    .............
    .............`,

    enemies: [
        { type: 'EnemyTankRapid', position: { x: 200, y: 250 }, angle: Math.PI / 2 },
        { type: 'EnemyTankRapid', position: { x: 500, y: 250 }, angle: Math.PI / 2 },
        { type: 'EnemyTankRapid', position: { x: 800, y: 250 }, angle: Math.PI / 2 }
    ]
};

const Level1: ILevel = {
    id: 'Level1',

    map: `X...........X
    .............
    .............
    .............
    O.O.O.O.O.O.O
    .O.O.O.O.O.O.
    .....X.X......
    ......X......
    .............
    O.O.O.O.O.O.O
    .O.O.O.O.O.O.
    ....SSSS.....
    X...........X`,

    enemies: [
        { type: 'EnemyTankStandard', position: { x: 200, y: 250 }, angle: Math.PI / 2 },
        { type: 'EnemyTankStandard', position: { x: 500, y: 250 }, angle: Math.PI / 2 },
        { type: 'EnemyTankStandard', position: { x: 800, y: 250 }, angle: Math.PI / 2 }
    ]
};

const Level2: ILevel = {
    id: 'Level2',

    map: `.............
    .............
    .............
    .....XX......
    .....XX......
    .............
    .............
    .............
    .............
    .............
    .............
    .............
    .............`,

    enemies: [
        { type: 'EnemyTankRapid', position: { x: 200, y: 250 }, angle: Math.PI / 2 },
        { type: 'EnemyTankRapid', position: { x: 500, y: 250 }, angle: Math.PI / 2 },
        { type: 'EnemyTankRapid', position: { x: 800, y: 250 }, angle: Math.PI / 2 }
    ]
};


const LevelRandom: ILevel = {
    id: 'LevelRandom',

    map: ``,

    enemies: [
        { type: 'EnemyTankStrong', position: { x: 200, y: 250 }, angle: Math.PI / 2 },
        { type: 'EnemyTankStrong', position: { x: 500, y: 250 }, angle: Math.PI / 2 },
        { type: 'EnemyTankStrong', position: { x: 800, y: 250 }, angle: Math.PI / 2 }
    ]
};

export const allLevels: ILevel[] = [Level1, Level2, LevelRandom];

