import { ILevel } from "../types/Level";
import { EnemyTankStandard, EnemyTankRapid, EnemyTankHeavy, EnemyTankStrong } from '../actors/EnemyTankClasses';

/*
    . = whithespace
    % = player spawnpoint
    * = enemy spawnpoint
    O = destrutible block

*/

const Level0: ILevel = {
    id: 'Level2',

    map: `.............
    .............
    .............
    .............
    .............
    .............
    .............
    .............
    .............
    .............
    .............
    .............
    .............`,

    enemies: [
        new EnemyTankRapid({ x: 200, y: 250 }, Math.PI / 2),
        new EnemyTankRapid({ x: 500, y: 250 }, Math.PI / 2),
        new EnemyTankRapid({ x: 800, y: 250 }, Math.PI / 2)
    ]
}

const Level1: ILevel = {
    id: 'Level1',

    map: `X...........X
    .............
    .............
    .............
    O.O.O.O.O.O.O
    .O.O.O.O.O.O.
    .....X.X......
    ......X......
    .............
    O.O.O.O.O.O.O
    .O.O.O.O.O.O.
    ....SSSS.....
    X...........X`,

    enemies: [
        new EnemyTankStandard({ x: 200, y: 250 }, Math.PI / 2),
        new EnemyTankStandard({ x: 500, y: 250 }, Math.PI / 2),
        new EnemyTankStandard({ x: 800, y: 250 }, Math.PI / 2)
    ]
}

const Level2: ILevel = {
    id: 'Level2',

    map: `.............
    .............
    .............
    .....XX......
    .....XX......
    .............
    .............
    .............
    .............
    .............
    .............
    .............
    .............`,

    enemies: [
        new EnemyTankRapid({ x: 200, y: 250 }, Math.PI / 2),
        new EnemyTankRapid({ x: 500, y: 250 }, Math.PI / 2),
        new EnemyTankRapid({ x: 800, y: 250 }, Math.PI / 2)
    ]
}

const LevelRandom: ILevel = {
    id: 'LevelRandom',

    map: ``,

    enemies: [
        new EnemyTankStrong({ x: 200, y: 250 }, Math.PI / 2),
        new EnemyTankStrong({ x: 500, y: 250 }, Math.PI / 2),
        new EnemyTankStrong({ x: 800, y: 250 }, Math.PI / 2)
    ]
};

export const allLevels: ILevel[] = [Level1, Level2, LevelRandom];

