export const mapLevel1 = `
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WW............WW............WWW
WW.WWWW.WWWWW.WW.WWWWW.WWWW.WWW
WW*WWWW.WWWWW.WW.WWWWW.WWWW*WWW
WW.WWWW.WWWWW.WW.WWWWW.WWWW.WWW
WW..........................WWW
WW.WWWW.WW.WWWWWWWW.WW.WWWW.WWW
WW.WWWW.WW.WWWWWWWW.WW.WWWW.WWW
WW......WW....WW....WW......WWW
WWWWWWW.WWWWW.WW.WWWWW.WWWWWWWW
WWWWWWW.WWWWW.WW.WWWWW.WWWWWWWW
WWWWWWW.WW..........WW.WWWWWWWW
WWWWWWW.WW.WWW--WWW.WW.WWWWWWWW
WWWWWWW.WW.WooooooW.WW.WWWWWWWW
...........WooooooW............
WWWWWWW.WW.WooooooW.WW.WWWWWWWW
WWWWWWW.WW.WWWWWWWW.WW.WWWWWWWW
WWWWWWW.WW..........WW.WWWWWWWW
WWWWWWW.WW.WWWWWWWW.WW.WWWWWWWW
WWWWWWW.WW.WWWWWWWW.WW.WWWWWWWW
WW............WW............WWW
WW.WWWW.WWWWW.WW.WWWWW.WWWW.WWW
WW*WWWW.WWWWW.WW.WWWWW.WWWW*WWW
WW...WW................WW...WWW
WWWW.WW.WW.WWWWWWWW.WW.WW.WWWWW
WWWW.WW.WW.WWWWWWWW.WW.WW.WWWWW
WW......WW....WW....WW......WWW
WW.WWWWWWWWWW.WW.WWWWWWWWWW.WWW
WW.WWWWWWWWWW.WW.WWWWWWWWWW.WWW
WW..........................WWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW`

export const mapLevel2 = `
`