/*
    . = whithespace
    % = player spawnpoint
    * = enemy spawnpoint
    O = destrutible block

*/


export const mapsBlueprints = [
    //Level0
    `.............
    .............
    .............
    .............
    .............
    .............
    .............
    .............
    .............
    .............
    .............
    .............
    .............`,

    //Level1
    `O.O.O.O.O.O.O
    .O.O.O.O.O.O.
    O.O.O.O.O.O.O
    .O.O.O.O.O.O.
    O.O.O.O.O.O.O
    .O.O.O.O.O.O.
    .............
    .............
    .............
    O.O.O.O.O.O.O
    .O.O.O.O.O.O.
    .............
    .............`

]

